### ISSUE TITLE
Question: Could this be used to re-encode files as well?

### ISSUE THREAD

**Issue by charliwest** [dcthomson/mkvdts2ac3.py#18]
Could this be set up to convert files to use x265 once downloaded?

**Comment by dcthomson** [comment]
All this script does is pull the DTS audio out of a mkv file and re-encode it to ac3 instead. So if you have an mkv file that has x265 video encoding and DTS audio, it should work on that.

But if you are trying to convert from another video format to x265 you would need to use something else. I would take a look at ffmpeg https://www.ffmpeg.org/
