### ISSUE TITLE
Feature request? Add to or replace existing AC3/DTS tracks with AAC track

### ISSUE THREAD

**Issue by gpsmit** [dcthomson/mkvdts2ac3.py#19]
Hi dcthomson,

I have been looking for a way to replace existing AC3 or DTS tracks with aac files.
The reason is that a lot of my iOS devices cannot play AC3. So streaming to content to my iOS devices is limited

Your script is the one that comes closest, as you can already add AAC audio when it finds a DTS track. Except, as it is now, it will not process anything for files which already have AC3. It seems to skip the add aac track step even though i force process them. Unless im doing something wrong.

Is there a way to achieve this: always add aac track to the file, even though it already has an AC3?
Im using your script in conjunction with NZGBET btw, but also on the command line it did not seem to add anything.

The script runs after every nzbget download, it would be great if it would always add an aac file to the downloaded files. Then my setup would be complete

Would love to hear from you,
Thanks so much,
gpsmit

**Comment by dcthomson** [comment]
I didn't like adding more and more to this script cuz its supposed to be for dts to ac3 (and it looked difficult to add this functionality to it without a lot of work), so I made: https://github.com/dcthomson/mkvac32aac.py
It's just a modification of the dts->ac3 script. I tested it with the following file:

original:
$ mkvmerge -i test/mkv-with-ac3.mkv 
File 'test/mkv-with-ac3.mkv': container: Matroska
Track ID 0: video (MPEG-4p10/AVC/h.264)
Track ID 1: audio (AC3/EAC3)
Global tags: 1 entry
Tags for track ID 0: 1 entry
Tags for track ID 1: 1 entry

added AAC:
$ mkvmerge -i mkv-with-ac3.mkv 
File 'mkv-with-ac3.mkv': container: Matroska
Track ID 0: video (MPEG-4p10/AVC/h.264)
Track ID 1: audio (AC3/EAC3)
Track ID 2: audio (AAC)
Global tags: 1 entry
Tags for track ID 0: 1 entry
Tags for track ID 1: 1 entry

I couldn't get it to work using either of the codecs: libvo_aacenc or libfdk_aac 
So I used the aac codec which is experimental.

Let me know if it works for you.

This should only run on files that it finds a AC3 audio track in while the other script should only run on files with a DTS track so you should be able to run them both one after the other in nzbget.

**Comment by gpsmit** [comment]
This is great man, thanks so much!
I'll check it out when i get back from work and report back.
Much appreciated!

Cheers,
gpsmit

**Comment by dcthomson** [comment]
Just checking, did that work out for you?

**Comment by gpsmit** [comment]
I have had a complete infrastructure failure for over a week at my house, its a nightmare. 
I cannot use anything, including my Raspberry download box, at the moment. A mechanic is scheduled to come by today. I'll check it out when everything comes back up today/tomorrow.

Again thanks for the help and sorry for the delay in reporting back!

**Comment by gpsmit** [comment]
Yes it works!
Thanks so much for your efforts.
Only sad thing is the raspberry pi isnt really up to the task.
I will deploy this on my regular computer though.

Again, thanks so much!

BTW im using the same aac codec (default in ffmpeg i believe) so it worked out just fine
